project:
  type: website
  execute-dir: project

website:
  title: "Projects"
  navbar:
    background: secondary
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Ajeets6
      - icon: linkedin
        href: https://www.linkedin.com/in/ajeetsingh6
    pinned: true
    collapse: false
  sidebar:
    style: "docked"
    collapse-level: 1
    search: true

    alignment: center
    contents:
    - file: posts/multi-modal-rag/rag.md

format:
  html:
    mainfont: "'Roboto Flex'"
    code-blocks: true
    embed-resources: false
    page-layout: article
    theme:
      dark: [darkly,dark.scss]
      light: [darkly,light.scss]
    include-in-header:
      file: header.html

    grid:
      sidebar-width: 300px
      body-width: 1000px
      margin-width: 300px
    css: styles.css



